faq/urls.py
from django.urls import path
from .views import faq

app_name = "faq"
urlpatterns = [
    path("faq/", faq, name="index"),
]

greencleanhome/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("faq.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from .views import home, calc_price, submit_form

app_name = "home"

urlpatterns = [
    path("", home, name="index"),
    path("calc-price/", calc_price, name="price"),
    path("submit-form/", submit_form, name="submit_form"),
]

faq/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
from django.utils.encoding import smart_text


class Home(models.Model):
    home_id = models.AutoField(primary_key=True)
    home_description = models.CharField(max_length=255, unique=True)
    home_size = models.CharField(max_length=255, unique=True)
    initial = models.CharField(max_length=15, verbose_name='Initial')
    weekly = models.CharField(max_length=15, verbose_name='Weekly')
    week2 = models.CharField(max_length=15, verbose_name='Every 2nd week')
    week3 = models.CharField(max_length=15, verbose_name='Every 3rd week')
    monthly = models.CharField(max_length=15, verbose_name='Monthly')

    class Meta:
        verbose_name = 'Home'
        verbose_name_plural = 'Homes'

    def __str__(self):
        return smart_text(self.home_description)

home/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    phone = forms.CharField(required=True)
    email = forms.CharField(required=True)
    message = forms.CharField(
        required=True, widget=forms.Textarea(attrs={"rows": 5, "cols": 5})
    )

    def clean(self):
        cleaned_data = super(ContactForm, self).clean()
        name = cleaned_data.get("name")
        email = cleaned_data.get("email")
        message = cleaned_data.get("message")
        if not name and not email and not message:
            raise forms.ValidationError("You have to write something!")
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({"placeholder": "Full name"})
        self.fields["phone"].widget.attrs.update({"placeholder": "Phone number"})
        self.fields["email"].widget.attrs.update({"placeholder": "Email address"})
        self.fields["message"].widget.attrs.update(
            {"placeholder": "Please type your message"}
        )
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "effect-9"

faq/views.py
from django.shortcuts import render


def faq(request):
    template = "faq/index.html"
    context = {}

    return render(request, template, context)

home/views.py
import requests
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.conf import settings

from .forms import ContactForm

bedrooms_dict = {
    "Studio": 2,
    "1 bedroom": 2.5,
    "2 bedrooms": 3,
    "3 bedrooms": 3.5,
    "4 bedrooms": 4,
    "5 bedrooms": 5.5,
}

bathrooms_dict = {
    "1 bathroom": 0.3,
    "2 bathrooms": 0.6,
    "3 bathrooms": 0.9,
    "4 bathrooms": 1.2,
    "5 bathrooms": 1.5,
}

cleaning_type_dict = {
    "Standard": 1,
    "Standard Plus": 1.3,
    "Deep Clean": 1.5,
    "Moving in/out": 1.8,
}


def home(request):
    template = "home/index.html"

    house_type = "Studio"
    bathrooms = "1 bathroom"
    cleaning_type = "Standard"

    price = calculator(house_type, bathrooms, cleaning_type)

    context = {
        "form": ContactForm(),
        "price": price,
        "google_data_site_key": settings.GOOGLE_DATA_SITE_KEY,
    }

    return render(request, template, context)


def submit_form(request):
    template = "home/index.html"
    form = ContactForm()
    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        email = request.POST.get("email")
        message = request.POST.get("message")
        recaptcha_response = request.POST.get("recaptcha")

        data = {
            "secret": settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            "response": recaptcha_response,
        }

        r = requests.post("https://www.google.com/recaptcha/api/siteverify", data=data)
        result = r.json()

        if result["success"]:
            form_name = name
            form_phone = phone
            form_email = email
            form_message = message
            subject = "website email"
            from_email = settings.EMAIL_HOST_USER
            to_email = [from_email]
            message = f"{form_name} {form_phone} {form_email} {form_message}"
            send_mail(subject, message, from_email, to_email, fail_silently=False)
            form = ContactForm()
            return HttpResponse("Form submitted")

    context = {
        "form": form,
    }

    return render(request, template, context)


@csrf_exempt
def calc_price(request):
    template = "home/includes/price.html"

    house_type = request.POST.get("house_type")
    bathrooms = request.POST.get("bathrooms")
    cleaning_type = request.POST.get("cleaning_type")

    price = calculator(house_type, bathrooms, cleaning_type)
    context = {"price": price}
    data = {"html": render_to_string(template, context)}

    return JsonResponse(data)


def calculator(bedrooms, bathrooms, cleaning_type):
    bedroom_time = bedrooms_dict.get(bedrooms)
    bathroom_time = bathrooms_dict.get(bathrooms)
    cleaning_type_multiplier = cleaning_type_dict.get(cleaning_type)
    rate = 50

    price = (bedroom_time + bathroom_time) * cleaning_type_multiplier * rate

    return round(price)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script
      src="https://kit.fontawesome.com/50d678538c.js"
      crossorigin="anonymous"
    ></script>
    <!-- Compiled and minified CSS -->

    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Roboto:300,400,500"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'styles/css/style.css' %}"
    />
  </head>

  <body>
    <nav>
      <a href="" class="toggle-nav">
        <span><i class="fas fa-bars"></i></span>
      </a>
      <!-- mobile nav -->
      <div class="navbar-mobile | bg-image">
        <!-- Mobile navbar title -->
        <div class="navbar-mobile__header">
          <h2 class="navbar-mobile__title">Green Clean Home</h2>
          <p class="navbar-mobile__subtitle">Eco-Friendly Cleaning</p>
        </div>
        <!-- Mobile navbar links -->
        <ul class="navbar-mobile__links | active">
          <!-- Home link -->
          <li class="navbar-mobile__link">
            <a href="{% url 'home:index' %}" class="navbar-mobile__link-tag">
              <span class="navbar-mobile__link-icon">
                <i class="fas fa-home"></i>
              </span>
              <span>Home</span>
            </a>
          </li>

          <!-- Contact Us link -->
          <li class="navbar-mobile__link">
            <a href="" class="navbar-mobile__link-tag">
              <span class="navbar-mobile__link-icon">
                <i class="fas fa-phone"></i>
              </span>
              <span>Contact Us</span>
            </a>
          </li>
          <!-- About Us link -->
          <li class="navbar-mobile__link">
            <a href="" class="navbar-mobile__link-tag">
              <span class="navbar-mobile__link-icon">
                <i class="fas fa-heart"></i>
              </span>
              <span>About Us</span>
            </a>
          </li>
          <!-- FAQ link -->
          <li class="navbar-mobile__link">
            <a href="{% url 'faq:index' %}" class="navbar-mobile__link-tag">
              <span class="navbar-mobile__link-icon">
                <i class="fas fa-question"></i>
              </span>
              <span>Frequently Asked Questions</span>
            </a>
          </li>
        </ul>
      </div>
      <!-- End of mobile navbar -->

      <!-- Start of regular navbar -->
      <div class="navbar">
        <ul class="navbar__links">
          <!-- Home link -->
          <li class="navbar__link">
            <a
              href="{% url 'home:index' %}"
              class="navbar__link-tag | navbar-home | enabled"
              >Home</a
            >
          </li>
          <!-- About us link -->
          <li class="navbar__link">
            <a
              href="{% url 'home:index' %}#section-b"
              class="navbar__link-tag | disabled"
              >About Us</a
            >
          </li>
          <!-- Prices link -->
          <li class="navbar__link">
            <a
              href="{% url 'home:index' %}#section-d"
              class="navbar__link-tag | disabled"
              >Prices</a
            >
          </li>
          <!-- Contact Us link -->
          <li class="navbar__link">
            <a
              href="{% url 'home:index' %}#section-e"
              class="navbar__link-tag | disabled"
              >Contact Us</a
            >
          </li>

          <!-- FAQ link -->
          <li class="navbar__link">
            <a href="{% url 'faq:index' %}" class="navbar__link-tag | enabled"
              >FAQ</a
            >
          </li>
        </ul>
      </div>
    </nav>
    {% block body %} {% endblock %}
    <footer id="footer" class="section">
      <div class="content">
        <div class="footer__top">
          <!-- footer title -->
          <div class="footer-title">
            <h2 class="footer-title__title">Green Clean Home</h2>
            <p class="footer-title__subtitle">Eco-Friendly Cleaning</p>
            <p class="footer-title__line"></p>
          </div>
          <!-- footer links -->
          <ul class="footer__links">
            <li class="footer__links__link">
              <a href="" class="">Home</a>
            </li>
            <li class="footer__links__link">
              <a href="">Rates & Services</a>
            </li>
            <li class="footer__links__link">
              <a href="">Contact Us</a>
            </li>
            <li class="footer__links__link">
              <a href="">About Us</a>
            </li>
            <li class="footer__links__link">
              <a href="{% url 'faq:index' %}">FAQ</a>
            </li>
          </ul>
        </div>
        <div class="footer-bottom">
          <p class="terms-conditions">
            2020 Green Clean Home. All rights reserved.
          </p>
          <p class="designed-by">
            Designed and developed by <span class="dev">prebenhesvik.com</span>
          </p>
        </div>
      </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.16.0/jquery.validate.js"></script>
    <script src="https://www.google.com/recaptcha/api.js"></script>
    <script src="{% static 'scripts/click-scroll.js' %}"></script>
    <!-- <script src="{% static 'scripts/form-validation.js' %}"></script> -->
    <script src="{% static 'scripts/submit-form.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'scripts/tabs.js' %}"></script> -->
    <script
      type="text/javascript"
      src="{% static 'scripts/main.js' %}"
    ></script>
  </body>
</html>

templates/faq/includes/mobile-nav.html
<nav class="mobile-faq-nav">
  <div class="drop-down-menu">
    <a href="" class="toggle-me"
      >TABLE OF CONTENT
      <i class="fa fa-angle-down fa-2x" aria-hidden="true"></i>
    </a>
    <div class="dropdown-items">
      <ul>
        <li class="dropdown-item"><a href="#section_1">General</a></li>
        <li class="dropdown-item">
          <a href="#section_2">Cleaning Details</a>
        </li>
        <li class="dropdown-item"><a href="#section_3">Billing</a></li>
        <li class="dropdown-item">
          <a href="#section_4">200% Satisfaction Guarantee</a>
        </li>
        <li class="dropdown-item">
          <a href="#section_5">Scheduling</a>
        </li>
        <li class="dropdown-item">
          <a href="#section_6">Cleaning Tips</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/faq/includes/page-header.html
<div class="page-header">
  <h2 class="title">Frequently Asked Questions</h2>
  <p class="faq-header-text">
    Here are some common questions we receive from our customers.
  </p>
  <p class="faq-header-text">
    If you don't find the answer to your question please don't hesitate to call
    us at <span class="accent-2">{{ phone}}</span> or email
    <span class="accent-2">{{email}}</span>.
  </p>
</div>

templates/faq/includes/regular-nav.html
<nav id="regular-faq-nav" class="regular-faq-nav">
  <p>Table of contents</p>
  <ul class="menu">
    <li class="faq-category"><a href="#section_1">General</a></li>
    <li class="faq-category">
      <a href="#section_2">Cleaning Details</a>
    </li>
    <li class="faq-category"><a href="#section_3">Billing</a></li>
    <li class="faq-category">
      <a href="#section_4">200% Satisfaction Guarantee</a>
    </li>
    <li class="faq-category"><a href="#section_5">Scheduling</a></li>
    <li class="faq-category"><a href="#section_6">Cleaning Tips</a></li>
  </ul>
</nav>

templates/faq/index.html
{% extends "base.html" %} {% block title %}FAQ{% endblock %} {% block body %}
<div class="container-faq">
  <!-- page header -->
  {% include "faq/includes/page-header.html" %}

  <div class="faq-content">
    <!-- div includes regular nav and mobile nav -->
    <div class="navigation">
      <!-- Mobile nav -->
      {% include "faq/includes/mobile-nav.html" %}
      <!-- regular nav -->
      {% include "faq/includes/regular-nav.html" %}
    </div>
    <!-- questions and answers -->
    {% include "faq/includes/questions_and_answers.html" %}
  </div>
</div>

{% endblock %}

templates/home/includes/about-us.html
<div class="section__title">
  <h2 class="section__title-text">About Us</h2>
  <p class="section__title-line"></p>
</div>
<div class="content">
  <ul class="cards">
    <li class="card">
      <div class="card__icon-group">
        <span class="card__icon">
          <i class="fas fa-users"></i>
        </span>
      </div>
      <div class="card__text">
        <h3 class="card__heading">Three and four person teams</h3>
        <p class="card__paragraph">Licensed, insured and bonded for ease of mind.</p>
      </div>
    </li>
    <li class="card">
      <div class="card__icon-group">
        <span class="card__icon">
          <i class="fas fa-map-marker"></i>
        </span>
      </div>
      <div class="card__text">
        <h3 class="card__heading">We serve San Antonio area</h3>
        <p class="card__paragraph">
          We currently have 12 local offices.
        </p>
      </div>
    </li>
    <li class="card">
      <div class="card__icon-group">
        <span class="card__icon">
          <i class="fas fa-brush"></i>
        </span>
      </div>
      <div class="card__text">
        <h3 class="card__heading">Home and office cleaning services</h3>
        <p class="card__paragraph">
          Standard or customized options to choose from.
        </p>
      </div>
    </li>

    <li class="card">
      <div class="card__icon-group">
        <span class="card__icon">
          <i class="fas fa-credit-card"></i>
        </span>
      </div>
      <div class="card__text">
        <h3 class="card__heading">Ease of payment</h3>
        <p class="card__paragraph">
          Major credit cards, cash and bitcoin accepted.
        </p>
      </div>
    </li>
  </ul>
  <!-- Button -->
  <a href="">
    <button id="btn-about-us" type="button" class="btn">
      Read More
    </button>
  </a>
</div>

templates/home/includes/contact-us.html
<div class="section__title">
  <h2 class="section__title-text">Contact Us</h2>
  <p class="section__title-line"></p>
</div>
<div class="content">
  <div class="contact-us">
    <div class="contact-us__info">
      <ul class="contact-us__details">
        <li class="contact-us__detail">
          <span class="icon">
            <i class="fas fa-phone"></i>
          </span>
          <div class="contact-card__text">
            <h3 class="heading">{{ phone}}</h3>
          </div>
        </li>
        <li class="contact-us__detail">
          <span class="icon">
            <i class="fas fa-envelope"></i>
          </span>
          <div class="contact-card__text">
            <h3 class="heading">{{ email}}</h3>
          </div>
        </li>
        <li class="contact-us__detail">
          <span class="icon">
            <i class="fas fa-map-marker-alt"></i>
          </span>
          <div class="contact-card__text">
            <h3 class="heading">5100 USAA Blvd</h3>
            <h3 class="heading">San Antonio, TX 78240</h3>
          </div>
        </li>
      </ul>
    </div>

    <!-- Contact form -->
    <div class="contact-us__form">
      <h3 class="form__heading">Leave us a message</h3>
      <form
        id="contact-form"
        action="/submit-form/"
        class=""
        method="POST"
        enctype="multipart/form-data"
        data-url=""
      >
        {% csrf_token %} {% for field in form %} {% if field.errors %}
        <div class="flex-form-group">
          {{ field }}
          <span class="focus-border">
            <i></i>
          </span>
          <p class="help-inline">
            {% for error in field.errors %} {{ error }} {% endfor %}
          </p>
        </div>
        {% else %}
        <div class="flex-form-group">
          {{ field }}
          <span class="focus-border">
            <i></i>
          </span>
        </div>
        {% endif %} {% endfor %} {% comment %}
        <div class="g-recaptcha" data-sitekey="{{google_data_site_key}}"></div>
        {% endcomment %}
        <button
          id=""
          type="submit"
          value="submit"
          class="btn-block button-send"
        >
          <span class="button-text">Send</span>
        </button>
      </form>
    </div>
  </div>
</div>

templates/home/includes/our-mission.html
<div class="section__title">
  <h2 class="section__title-text">Our mission</h2>
  <p class="section__title-line"></p>
</div>
<div class="content">
  <div class="text-box">
    <p class="text-box__text">
      At Green Home and Office, eco-friendly practices aren't just a fad, they are how we've done
      business from the start. We operate in an environmentally responsible way and use cleaning
      methods that are safe for our clients, safe for their families and safe for pets and the
      planet.
    </p>
    <p class="text-box__text">
      We help you take the pressure off and leave you to do more of the things you love. We'd be
      honored to have your business and do our parts together.
    </p>
  </div>
</div>

templates/home/includes/price-calc.html
<div class="section__title">
  <h2 class="section__title-text">Pricing</h2>
  <p class="section__title-line"></p>
</div>
<div class="content">
  <div class="price-calc">
    <!-- House type -->
    <div class="select-wrapper">
      <span class="absolute"><i class="fas fa-angle-down"></i></span>
      <select name="" id="house-type" class="get-quote">
        <option value="Studio" selected>Studio</option>
        <option value="1 bedroom">1 bedroom</option>
        <option value="2 bedrooms">2 bedrooms</option>
        <option value="3 bedrooms">3 bedrooms</option>
        <option value="4 bedrooms">4 bedrooms</option>
        <option value="5 bedrooms">5 bedrooms</option>
      </select>
    </div>
    <!-- Number of bathrooms -->
    <div class="select-wrapper">
      <span class="absolute"><i class="fas fa-angle-down"></i></span>
      <select name="" id="bathroom" class="get-quote">
        <option value="1 bathroom" selected>1 bathroom</option>
        <option value="2 bathrooms">2 bathrooms</option>
        <option value="3 bathrooms">3 bathrooms</option>
        <option value="4 bathrooms">4 bathrooms</option>
        <option value="5 bathrooms">5 bathrooms</option>
      </select>
    </div>
    <!-- Cleaning type -->
    <div class="select-wrapper">
      <span class="absolute"><i class="fas fa-angle-down"></i></span>
      <select name="" id="cleaning-type" class="get-quote">
        <option value="Standard" selected>Standard</option>
        <option value="Standard Plus">Standard Plus</option>
        <option value="Deep Clean">Deep Clean</option>
        <option value="Moving in/out">Moving in/out</option>
      </select>
    </div>
    <div class="price-box">
      {% include 'home/includes/price.html' %}
    </div>
  </div>
</div>

templates/home/includes/price.html
{% load static %}
<p class="price">From ${{ price }}</p>

templates/home/includes/showcase.html
<div class="showcase__bg-image | bg-image">
  <div class="showcase__frame">
    <div class="showcase__title">
      <h5 class="showcase__pre-title-text">Welcome to</h5>
      <h1 class="showcase__title-text">Green Clean Home</h1>
      <p class="showcase__text-separator"></p>
      <p class="showcase__post-title-text">Eco-Friendly Cleaning</p>
    </div>
  </div>
</div>

templates/home/index.html
{% extends "base.html" %} {% block body %}
<!-- Showcase start -->
<div id="showcase">
  {% include "home/includes/showcase.html" %}
</div>

<!-- Section - Our Mission  -->
<div id="section-a" class="section">
  {% include "home/includes/our-mission.html" %}
</div>

<!-- About Us section -->
<div id="section-b" class="section">
  {% include "home/includes/about-us.html" %}
</div>

<!-- Start of section-e -->
<div id="section-d" class="section">
  {% include "home/includes/price-calc.html" %}
</div>

<!-- Section e -->
<div id="section-e" class="section">
  {% include "home/includes/contact-us.html" %}
</div>

{% endblock %}